#!/usr/bin/env python3
"""
Helper script to set up Yahoo Finance API credentials in .env file.
Run this script to create or update your .env file with Yahoo Finance credentials.
"""

import os
from pathlib import Path

def create_env_file():
    """Create .env file with Yahoo Finance credentials."""
    env_path = Path(__file__).parent / ".env"
    
    # Check if .env already exists
    if env_path.exists():
        print(f"⚠️  .env file already exists at {env_path}")
        response = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if response != "yes":
            print("❌ Aborted. Existing .env file preserved.")
            return
    
    # Yahoo Finance API credentials
    credentials = {
        "YAHOO_APP_ID": "Z8JuxEOd",
        "YAHOO_CLIENT_ID": "dj0yJmk9dllZZnU5ZVE2anVlJmQ9WVdrOVdqaEtkWGhGVDJRbWNHbzlNQT09JnM9Y29uc3VtZXJzZWNyZXQmc3Y9MCZ4PWNi",
        "YAHOO_CLIENT_SECRET": "efb70107386dab86d8dbf604e6d8b63acbad8d8e"
    }
    
    # Write .env file
    with open(env_path, "w") as f:
        f.write("# Yahoo Finance API OAuth Credentials\n")
        f.write("# Generated by setup_yahoo_env.py\n\n")
        for key, value in credentials.items():
            f.write(f"{key}={value}\n")
    
    print(f"✅ Created .env file at {env_path}")
    print("\n📝 Credentials added:")
    print(f"   YAHOO_APP_ID={credentials['YAHOO_APP_ID']}")
    print(f"   YAHOO_CLIENT_ID={credentials['YAHOO_CLIENT_ID'][:20]}...")
    print(f"   YAHOO_CLIENT_SECRET={'*' * len(credentials['YAHOO_CLIENT_SECRET'])}")
    print("\n✅ Setup complete! You can now run test_yahoo_oauth.py to test the connection.")

if __name__ == "__main__":
    create_env_file()

